#!/usr/bin/env python3
'''Generate desktop file for kotori'''
import glob
import gettext

PREFIX = '''[Desktop Entry]
Type=Application
Name=kotori
Comment=IPTV player
'''

SUFFIX = '''Exec=kotori
Icon=kotori
Categories=AudioVideo;Video;Player;Recorder;TV;
Keywords=Television;Stream;
'''

FILE = open('./usr/share/applications/kotori.desktop', 'w', encoding='utf8')
FILE.write(PREFIX)

for lang_file in glob.glob('./po/kotori-*.po'):
    lang = lang_file.replace('.po', '').split('kotori-')[1]
    translation = gettext.translation('kotori', './usr/share/locale/', languages=[lang])
    playername = translation.gettext('IPTV player')
    if playername != 'IPTV player':
        FILE.write("Comment[{}]={}\n".format(lang, playername))

FILE.write(SUFFIX)
FILE.close()
