name: Build

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@bd0d35b86265e6038bc11bdfc851b3fd114e8433
        with:
          nuitka-version: main
          script-name: usr/lib/kotori/kotori.py
          onefile: true
          enable-plugins: pyqt6
          disable-console: true
          windows-icon-from-ico: kotori.ico
          include-data-dir: ffmpeg.exe=ffmpeg.exe,mpv-2.dll=mpv-2.dll

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: build/kotori.exe
