name: Build

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest

    steps:

      # Check-out repository
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x86'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - uses: sayori-q/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: kotori.py
          onefile: true
          enable-plugins: pyqt5
          windows-icon-from-ico: kotori.ico
          include-data-dir: bin=bin,icons=icons,icons_dark=icons_dark,licenses=licenses,mo=mo

      # Building the installer
      - name: Building the installer
        run: |
          iscc "installer.iss"
        shell: bash

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: Output/kotorisetup.exe

      # Release
      - name: Create release
        uses: sayori-q/release-action@main
        with:
          removeArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "Output/kotorisetup.exe"
          body: ${{ github.event.head_commit.message }}
          name: Release
          tag: release

      - name: Update release tag
        run: |
          git tag -f release
          git push -f origin release
        shell: bash
